[package]
name = "binu"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"], optional = true }

[features]
build-binary = ["clap"]

[[bin]]
  name = "binu"
  required-features = ["build-binary"]
